# HTGAnalyzer

## Overview

The `HTGAnalyzer` package provides tools for analyzing HTG Transcriptomic data. It includes functions for quality control, differential expression analysis, gene set enrichment analysis, and more.

## SUPLEMENTARY_OUTPUT Folder

The `SUPLEMENTARY_OUTPUT` folder contains all the results generated by the `HTG_auto` function. This function processes the input data and produces various outputs that are stored in this folder. 

### Input Data

The results in `SUPLEMENTARY_OUTPUT` are generated using the following inputs:

- **counts_data**: The path to the counts data file.
- **AnnotData**: The path to the annotation data file.

### Example Usage

Below is an example of how to use the `HTG_auto` function to generate results that will be saved in the `SUPLEMENTARY_OUTPUT` folder:

```r
result <- HTG_auto(
    counts_file_path = "~/HTGAnalyzer/counts.xlsx",  # Path to counts data
    file_type = "HTG",  # Type of count file
    AnnotData_file_path = "~/HTGAnalyzer/annotdata.xlsx",  # Path to annotation data
    pattern = "^NC-|^POS-|^GDNA-|^ERCC-",  # HTG probes with these prefixes
    save_csv = TRUE,
    csv_file = "QC_results.csv",
    design_formula = "HPV_status",  # Design formula
    genes_to_use = c("CCND1", "MMP10", "CTTN"),
    heatmap_columns = c("HPV_status", "Ciclina_D1"),  # Columns for heatmap
    contrast = c("HPV_status", "Positive", "Negative"),  # Contrast for differential analysis
    pCutoff = 5e-2,
    variable_01 = "Recurrence_01",  # Variable for analysis
    time = "Time_to_death_surv",  # Time for survival analysis
    DEA = TRUE,
    remove_outliers = TRUE,
    GSEA = TRUE,
    generate_heatmap = TRUE,
    TME = TRUE,
    survival_analysis = TRUE
)
```
