name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install remotes and BiocManager
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")'

      - name: Install Bioconductor dependencies
        run: |
          Rscript -e 'BiocManager::install(c("DESeq2", "apeglm", "ComplexHeatmap", "org.Hs.eg.db", "clusterProfiler", "enrichplot"))'

      - name: Install GitHub dependencies
        run: |
          Rscript -e 'remotes::install_github("dviraran/xCell", auth_token = Sys.getenv("GITHUB_PAT"))'
          Rscript -e 'remotes::install_github("GfellerLab/EPIC", auth_token = Sys.getenv("GITHUB_PAT"))'
          Rscript -e 'remotes::install_github("IOBR/IOBR", auth_token = Sys.getenv("GITHUB_PAT"))'
          Rscript -e 'remotes::install_github("omnideconv/immunedeconv", auth_token = Sys.getenv("GITHUB_PAT"))'
          Rscript -e 'remotes::install_github("kevinblighe/EnhancedVolcano", auth_token = Sys.getenv("GITHUB_PAT"))'

      - name: Install remaining R package dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Check the package
        run: R CMD check --as-cran .



