name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        version: 'latest'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

    - name: Install remotes and BiocManager
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'install.packages("BiocManager")'

    - name: Install GitHub dependencies with PAT
      env:
        GITHUB_PAT: ${{ secrets.MY_GITHUB_TOKEN }} # Asegúrate de que el token esté correctamente configurado
      run: |
        Rscript -e 'remotes::install_github("dviraran/xCell")'
        Rscript -e 'remotes::install_github("GfellerLab/EPIC")'
        Rscript -e 'remotes::install_github("IOBR/IOBR")'
        Rscript -e 'remotes::install_github("omnideconv/immunedeconv")'
        Rscript -e 'remotes::install_github("kevinblighe/EnhancedVolcano")'

    - name: Install remaining R package dependencies
      run: Rscript -e "remotes::install_deps(dependencies = TRUE)"

    - name: Check the package
      run: R CMD check --as-cran .
