name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        version: 'latest'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev
    
    - name: Install R dependencies from CRAN
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
    
    - name: Install GitHub packages
      run: |
        Rscript -e "remotes::install_github('omnideconv/immunedeconv')"
        Rscript -e "remotes::install_github('dviraran/xCell')"
        Rscript -e "remotes::install_github('GfellerLab/EPIC')"
        Rscript -e "remotes::install_github('IOBR/IOBR')"
        Rscript -e "remotes::install_github('kevinblighe/EnhancedVolcano')"
    
    - name: Build vignettes
      run: |
        Rscript -e "devtools::build_vignettes()"

    - name: Check
      run: R CMD check --as-cran .
