name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        version: 'latest'

    - name: Install R dependencies from CRAN, Bioconductor, and GitHub
      run: |
        Rscript -e 'install.packages("BiocManager")'
        Rscript -e 'BiocManager::install(c("org.Hs.eg.db", "SummarizedExperiment", "DESeq2", "EnhancedVolcano", "clusterProfiler", "enrichplot", "ComplexHeatmap", "apeglm"))'
        Rscript -e 'remotes::install_github("dviraran/xCell")'
        Rscript -e 'remotes::install_github("GfellerLab/EPIC")'
        Rscript -e 'remotes::install_github("IOBR/IOBR")'
        Rscript -e 'remotes::install_github("omnideconv/immunedeconv")'

    - name: Install other package dependencies
      run: Rscript -e "remotes::install_deps(dependencies = TRUE)"

    - name: Check the package
      run: R CMD check --as-cran .

