name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        version: '4.1'  # Cambia esto a la versión que prefieras
    - name: Install dependencies
      run: |
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
    - name: Check
      run: R CMD check --as-cran .
